replicaCount: 3

image:
  repository: /projecta
  tag: 'latest'
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true
  annotations: {}
  name: ''

resources:
  limits:
    cpu: '100m'
  requests:
    cpu: '250m'

tolerations:
  - key: dedicated
    value: apps
    operator: Equal
    effect: NoSchedule

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 60

alb:
  enabled: true
  host: project

ingress:
  enabled: false
  className: 'nginx'
  annotations:
    cert-manager.io/issuer: 'letsencrypt-prod'

  hosts:
    - host: "project.onexidp.com"
      paths:
        - path: '/'
          pathType: Prefix

  tls:
    - hosts:
        - "project.onexidp.com"
      secretName: 'tls-secret'

letsencrypt:
  enabled: true
  email: 'aram@ideatolife.me'
db:
  enabled: true
livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 3

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3
  timeoutSeconds: 3
